### ISSUE TITLE
Use simple string for "type" in CloudEvent

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#107]
**Problem description**
I am looking from a developer POV and we are using code-generators to generate the code based on the CAMARA specifications.
When generating enums, e.g. here SubscriptionEventType, they will be generated like

```java
  ROAMING_STATUS("org.camaraproject.device-status.v0.roaming-status"),
  
  ROAMING_ON("org.camaraproject.device-status.v0.roaming-on"),
  
  ROAMING_OFF("org.camaraproject.device-status.v0.roaming-off"),

  ....
```

The in the spec described enums cannot be used in the CloudEvent, as we want here the String (e.g. org.camaraproject.device-status.v0.roaming-status).

```yaml
    SubscriptionEventType:
      type: string
      description: |
        roaming-status - Event triggered when the device switch from roaming ON to roaming OFF and conversely

        roaming-on - Event triggered when the device switch from roaming OFF to roaming ON

        roaming-off - Event triggered when the device switch from roaming ON to roaming OFF

        roaming-change-country - Event triggered when the device in roaming change country code

        connectivity-data - Event triggered when the device is connected to the network for Data usage.

        connectivity-sms - Event triggered when the device is connected to the network for SMS usage

        connectivity-disconnected - Event triggered when the device is not connected.

        subscription-ends - Event triggered when the subscription is terminated
      enum:
        - org.camaraproject.device-status.v0.roaming-status
        - org.camaraproject.device-status.v0.roaming-on
        - org.camaraproject.device-status.v0.roaming-off
        - org.camaraproject.device-status.v0.roaming-change-country
        - org.camaraproject.device-status.v0.connectivity-data
        - org.camaraproject.device-status.v0.connectivity-sms
        - org.camaraproject.device-status.v0.connectivity-disconnected
        - org.camaraproject.device-status.v0.subscription-ends

    CloudEvent:
      <...>
      properties:
       <...>
        type:
          $ref: "#/components/schemas/SubscriptionEventType"
```

**Possible evolution**
With this change we are not forced anymore to provide a Enum (e.g. ROAMING_STATUS), but can use the value of this enum (e.g. org.camaraproject.device-status.v0.roaming-status)

```yaml
        type:
          type: string
          description: Specifies the type of event for which the event will be sent.
```

**Comment by sachinvodafone** [comment]
I have requested our DevOps team to confirm if they encounter the same challenge. I will provide confirmation on this matter soon.

**Comment by maxl2287** [comment]
@sachinvodafone any new information from the DevOps-team?
@akoshunyadi / @bigludo7 can we talk about that again to just make the type as "string" in CloudEvent?

**Comment by shilpa-padgaonkar** [comment]
https://github.com/camaraproject/Commonalities/issues/149

**Comment by bigludo7** [comment]
@maxl2287 my colleague Patrice put a comment here: https://github.com/camaraproject/Commonalities/issues/159
Very interested on your feedback ... in order to understand the issue.

**Comment by maxl2287** [comment]
I will close this issue as it was already discussed with @shilpa-padgaonkar.
