### ISSUE TITLE
Request for Addition of "last_updated_timestamp" Field in CAMARA DeviceStatus API

### ISSUE THREAD

**Issue by Sachinsiso** [camaraproject/DeviceStatus#110]
**Problem Description**
The CAMARA version of the current DeviceStatus API lacks a crucial "ageOfInformation" or "last_updated_timestamp" field, resulting in inconsistent behavior across vendors. This absence poses challenges for application developers in determining the freshness of roaming status data.

**Expected Behavior**
Propose the addition of a "last_updated_timestamp" or similar field in the API response to indicate when the roaming status information was last updated. 

```
roaming: true
countryCode: 262
countryName: ["DE"]
last_updated_timestamp: “2018-04-05T17:31:00Z"
```

**Alternative Solution**
Explore and discuss any alternative approaches or fields that could address the issue. Consider other methods or data points that might serve the same purpose, assessing their feasibility and effectiveness.

**Additional Context**
NA

**Comment by bigludo7** [comment]
Hi @Sachinsiso 
Do you expect to provide the latest date of the status change or the date of the last check ?

I mean, suppose I switched in roaming mode Jan 15 at 6:38 
Now  we are Feb 14 12:25

I make a request.
Suppose backend provide the information of current roaming situation on the fly
We agree that this lastRoamingCheckTime" should be Feb 14 12:25 ?

**Comment by sachinvodafone** [comment]
Hi @bigludo7 , When verifying a device's roaming status through some central database such as HSS which keeps the correct status of device at all time, the recorded "lastRoamingCheckTime" will be established as "Feb 14 12:25."

In specific situations, the provider autonomously updates local roaming information upon receiving Diameter and SS7 signaling files. This update occurs both when a person initially enters the roaming state and whenever there is a signal change during roaming.

For instance, if an individual switched to roaming on "Jan 15 at 6:38," the system notes the "last_updated_timestamp" in its local repository at the time of this change. If the system checks the roaming status simultaneously, the "lastRoamingCheckTime" would be "Jan 15 at 6:38."  same as "last_updated_timestamp".

However, if their signal changes from 4G to 5G (or vice versa) on "Jan 20 at 7:00," the system receives updated Diameter/SS7 signal files, updating the "last_updated_timestamp" to "Jan 20 at 7:00." In this case, the "lastRoamingCheckTime" would then reflect "Jan 20 at 7:00." same as "last_updated_timestamp".

**Comment by mhfoo** [comment]
"Date of the last check Scenario" and "Latest date of the status change" should be two different parameters

"Date of the last check Scenario" is like HTTP Response Header: Last-Modified

cc: @eric-murray for your comments pls.

**Comment by sachinvodafone** [comment]
Hi @mhfoo , we have introduced the "lastRoamingCheckTime" feature to help us keep track of the last time we checked a device's roaming status.
Different service providers may have varying preferences when it comes to checking roaming status. Some could have possibility to check real-time roaming status, while others find it more valuable to refer to historical data. At Vodafone, we maintain a comprehensive database (historical) of devices in roaming, constantly updating it with accurate signal information as devices switch between 3G, 4G, and 5G networks. In our approach, we share the "lastRoamingCheckTime" specifically when there's a change in signal during roaming, indicating the most recent update to the device's roaming information.

It's crucial to understand that this concept differs significantly from the 'HTTP Response Header: Last-Modified' you might be acquainted with. They serve entirely different purposes and shouldn't be conflated.

**Comment by sachinvodafone** [comment]
Based on our discussion today regarding the importance of the "lastChecked" feature, here's my additional comment to provide further insight into the situation: 

Providers can try different ways to share roaming and connectivity info (Real time or Historical ). But sometimes (historical), there's a chance (like 0.1%) that the data might not be completely right. 

This situation can comes when a provider doesn't keep accurate info about roaming and connectivity, especially when they rely on specific sources for data, there's a chance that the data might not be completely accurate. For example, if the provider misses out on important signals indicating someone's back in their home country, the info becomes outdated and might not accurately show the client's status.

That's why adding a feature like "lastChecked" is important  as it can enhance the client's confidence level by indicating when the information was last verified.

**Comment by QaunainM** [comment]
Regarding Use cases for Device Status, having something like a lastUpdated timestamp would be useful.  Examples:

- Bank (or any institution) can run a check against numbers every x months to see if their customers phone numbers still exist (IF a number has not been connected to a network for 4+ months its probably doesn't exist)

- Communication / Marketing departments that use SMS / Voice can check if their users phone numbers are active, sothey can clean their lists and reduce usage costs (DeviceStatus check vs SMS pricing would need to be factored in here)

- Alarm systems (Base station, car trackers, etc) and other IoT devices can get logs of when their devices were last detectable to the network. Currently its seems to be a real-time true/false which doesn't give the history.
