### ISSUE TITLE
`subscriptionExpireTime` is declared as "required" in the subscription-ends - note, but is optional currently

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#116]
**Problem description**
[](https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L82-L84)

In the note for a subscription-ends event the `subscriptionExpireTime` is declared as "required by the requester".
But this request-parameter in POST /subscriptions is not mandatory. 

**Expected behavior**
Remove "required by the requester".

**Alternative solution**
Add `subscriptionExpireTime` as mandatory parameter

**Additional context** 

##### subscriptionExpireTime is optional

```yaml
CreateSubscription:
      description: The request for creating a Device Status event subscription
      type: object
      required:
        - webhook
        - subscriptionDetail
      properties:
        subscriptionDetail:
          $ref: "#/components/schemas/SubscriptionDetail"
        subscriptionExpireTime:
          type: string
          format: date-time
          example: 2023-01-17T13:18:23.682Z
          description: The subscription expiration time in date-time format.
        webhook:
          $ref: "#/components/schemas/Webhook"
```

**Comment by sachinvodafone** [comment]
Referring to the "subscription end" event outlined in the API guidelines as

> Specific event notification type "subscription-ends" is defined to inform listener about subscription termination. It is used when the subscription expire time (required by the requester) has been reached or if the API server has to stop sending notification prematurely. For this specific event, the data must feature terminationReason attribute.

So I believe , it aligns well with "subscription-ends," signifying that the "subscriptionExpireTime" should always be provided by the requester to make it effect.

**Comment by maxl2287** [comment]
Hi @sachinvodafone,

I reference now to the discussion with @bigludo7: 
https://github.com/camaraproject/DeviceStatus/discussions/105

What do you think about that?
Should it still be optional?

**Comment by sachinvodafone** [comment]
I do have some confusion over "subscriptionExpireTime" and "expiresAt" so created a discussion [147](https://github.com/camaraproject/Commonalities/discussions/147)
