### ISSUE TITLE
Send a CloudEvent when DELETE `/subscriptions/{subscriptionId}`

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#117]
**Problem description**
Currently there is no description about a CloudEvent when the subscription will be deleted by a User via  DELETE `/subscriptions/{subscriptionId}`.

**Possible evolution**

- Update the description of  `DELETE /subscriptions/{subscriptionId´ to mention that a CloudEvent will be send as well.
- Add a `terminationReason` like `DELETE_REQUESTED`

see how QoD v0.10.0 is doing it when the user requested a deletion before subscription-expired.

https://github.com/camaraproject/QualityOnDemand/blob/v0.10.0/code/API_definitions/qod-api.yaml#L918

**Comment by akoshunyadi** [comment]
The same as this in DeviceLocation https://github.com/camaraproject/DeviceLocation/issues/141 , there SUBSCRIPTION_DELETED has been proposed, which I would prefer here too.
DELETE_REQUESTED suggests that there will be another event with _DELETED.

**Comment by bigludo7** [comment]
Look good for me but I check consistence with Device location (https://github.com/camaraproject/DeviceLocation/issues/141) where same issue but not yet resolved.
