### ISSUE TITLE
Bugfix release v0.5.1

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#122]
**Problem description**
The release v0.5.0 contains a few bugs which should be corrected in a v0.5.1.
The release should be branched from the main branch, so no other commits should be performed before.

Content:
- [fix: move "countryCode" out of "device" in ROAMING_CHANGE_COUNTRY-example](https://github.com/camaraproject/DeviceStatus/pull/106) - merged
- [fix: add missing "subscriptionId" in "RoamingStatus"-data for CloudEvent](https://github.com/camaraproject/DeviceStatus/pull/109) - merged
- [fix: change description that subscriptionExpireTime is optional](https://github.com/camaraproject/DeviceStatus/pull/120) - merged
- PRxx typo in error 400
- [Updated in-line documentation for Roaming to clarify that country information can optionally be returned in the response](https://github.com/camaraproject/DeviceStatus/pull/127)

**Expected action**
- merge all necessary PRs
- create PR for release preparation
- create release

**Additional context**

**Comment by hdamker** [comment]
@akoshunyadi This is done and can be closed, right?

**Comment by akoshunyadi** [comment]
> @akoshunyadi This is done and can be closed, right?

That's correct, thanks!
