### ISSUE TITLE
When roaming status is true, is it mandatory to return both countryCode and countryName?

### ISSUE THREAD

**Issue by trehman-gsma** [camaraproject/DeviceStatus#124]
Context is the response object for `POST /roaming` [v0.5.0](https://github.com/camaraproject/DeviceStatus/blob/v0.5.0/code/API_definitions/device-status.yaml#L452):

```
    RoamingStatusResponse:
      type: object
      required:
        - roaming
      properties:
        roaming:
          $ref: "#/components/schemas/ActiveRoaming"
        countryCode:
          $ref: "#/components/schemas/CountryCode"
        countryName:
          $ref: "#/components/schemas/CountryName"
```

When `roaming` is returned as `true`, is it mandatory to also return both `countryCode` and `countryName`?

Could an operator choose to omit `countryCode` and `countryName` for privacy reasons?

**Comment by sachinvodafone** [comment]
Hi @trehman-gsma , as per specification , only 'roaming' (true or false) field  is required and other two (countryCode & countryName) are optional.

**Comment by trehman-gsma** [comment]
Hi @sachinvodafone,

The [in-line documentation in the spec](https://github.com/camaraproject/DeviceStatus/blob/v0.5.0/code/API_definitions/device-status.yaml#L19) currently states: `when the device is in roaming situation, visited country information is send back in the response.`

Some may imply this to mean that country information has to be returned when the device is roaming. Do you think the doc needs updating?

**Comment by sachinvodafone** [comment]
Hi @trehman-gsma  Thank you for pointing out the oversight. As per the documentation, it makes sense to include countryName and countryCode in the response when the device is in roaming. I can't recall any privacy usecase where the API server should omit these values. In such situations (if any), the API response should adhere to the specific "purpose of accessing the data," outlined in the “[IdentityandConsentManagement](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#purposes:~:text=BE%20EDITED/COMPLETED%5D-,Purposes,-A%20purpose%20declares)” documentation. This might involve defining two different scopes—one to send only the roaming status and the other to send all three attributes—or alternatively, defining two separate endpoints. However, it's essential to highlight and assess these use cases (if any) to determine their relevance, and real-world applicability to make any change in our current design/specification. _So as per my view , there's no need to make any changes at this point, considering that the API should consistently sends countryName and countryCode when the device is in roaming._

**Comment by trehman-gsma** [comment]
This issue was discussed during DeviceStatus meeting on 13-03-24. It was agreed that country information is optional in cases of roaming=true. PR #127 created to update documentation.

**Comment by trehman-gsma** [comment]
Hello @sachinvodafone @bigludo7 @akoshunyadi,

I have a related question on top of what was discussed during the DeviceStatus meeting on 13-03-24. I can create a new issue if required.

When roaming status is **false**, can country information also be optionally returned?

**Comment by bigludo7** [comment]
Hello @trehman-gsma 
Looking in the API documentation:

> Country : Country code and name - visited country information, provided if the device is in roaming situation.

So I do not expect country in not roaming situation but this is perhaps unfair to deny conformance.

The major point for me is that country information is optional (even for roaming situation) and we need to be very clear to the API consumer that this API cannot be considered as a sure thing to get the country where the device is.
