### ISSUE TITLE
What should the API return if more than one device identifier is sent and they don't belong to the same device?

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/DeviceStatus#130]
What should the API return if, for example, the client sends in the request body a phoneNumber and a networkAccessIdentifier that don't belong to the same device?

With the current implementation I'm thinking about a 400 INVALID_ARGUMENT. Should we have an specific error? DEVICE_IDENTIFIER_MISMATCH or something like that?

what do you think?

**Comment by nickvenezia** [comment]
"Timestamp - Device Identifier -  Last Seen" 
"Timestamp - Device Identifier - First Seen"

This would help a mobile game developer keep the user profile in-sync across devices is added to that user gamer profile. 

When mismatch developer can trigger an authorization flow.

**Comment by fernandopradocabrillo** [comment]
closing since it is being discussed in commonalities
