### ISSUE TITLE
Extend: Device Status Connectivity with Standard

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/DeviceStatus#143]
If there is a valid Data connection established the API should also inform about the Standard with which the device is connected. (2G, 3g, 4g , 5gnsa, 5gsa) 

This is helping developers to get a better insight about the connection status.

**Comment by sachinvodafone** [comment]
I'm concerned about combining connectivity status and network standard information into a single API. I believe keeping them separate would make the API easier to understand and use. Users could then choose which information they need without unnecessary complexity. 

Consider a scenario where the network element responsible for providing network standard information differs from the one handling connectivity status. Attempting to merge these distinct pieces of information into a single response would pose significant challenges and complexities. It's comparable to amalgamating data from two disparate databases with different schemas, a task feasible but laden with unnecessary complexity and the risk of potential points of failure

**Comment by QaunainM** [comment]
I haven;t factored in the point that @sachinvodafone mentioned above, but this would be very useful as it means the DeviceStatus API provides a bit more information that helps developer know when they should invoke other APIs. 

For example, if the user only has 2G then we know now to invoke QoD for them.

For developers it can means less APIs to call and reduced costs, but this is without factoring in points that @sachinvodafone  mentioned

**Comment by murthygorty** [comment]
Hi @akoshunyadi , is it possible to add this to 0.6.0 list, instead of 0.7.0 -> when are each of these targeted for (roughly?)

**Comment by akoshunyadi** [comment]
> Hi @akoshunyadi , is it possible to add this to 0.6.0 list, instead of 0.7.0 -> when are each of these targeted for (roughly?)

@murthygorty if we have an approved PR in time, then why not. The API version 0.6.0 (actually the splitted APIs with possible other versions) should be part of the upcoming fall metarelease, so we should have the first RC at middle/end of June.

**Comment by murthygorty** [comment]
> > Hi @akoshunyadi , is it possible to add this to 0.6.0 list, instead of 0.7.0 -> when are each of these targeted for (roughly?)
> 
> @murthygorty if we have an approved PR in time, then why not. The API version 0.6.0 (actually the splitted APIs with possible other versions) should be part of the upcoming fall metarelease, so we should have the first RC at middle/end of June.

Super, this is great info for me @akoshunyadi -> also good to know that we are targeting 0.6.0 for the fall release. Got the input.
@gmuratk @NoelWirzius

**Comment by NoelWirzius** [comment]
@sachinvodafone  im supporting this idea and see also that this could be in two single APIs/Endpoints. 

1. Connection Standard
2. Connection Standard subscription

I guess also the subscription model makes sense here, so developers are getting a notification, when sth. is changing and then can adjust their applications

**Comment by NoelWirzius** [comment]
wrong button :)

**Comment by akoshunyadi** [comment]
Do we have an idea how the API could be implemented?

**Comment by gmuratk** [comment]
I added a 'draft' PR for this feature request.  Currently it's lacking the subscriptions.

**Comment by hdamker** [comment]
@NoelWirzius @camaraproject/device-status_maintainers:

There is currently an overlap with an PR within ConnectivityInsights (see issue https://github.com/camaraproject/ConnectivityInsights/issues/48 which I have created there). One cause of this overlap is that neither DeviceStatus nor ConnectivityInsights has raised within APIBacklog their intent to define such API and that they want to include it into the scope of their Sub Project. 

My proposal would be to create an issue within APIBacklog for the scope enhancement and use that as a trigger for the discussion in which Sub Project the API will be allocated.

**Comment by Kevsy** [comment]
> There is currently an overlap with an PR within ConnectivityInsights (see issue [camaraproject/ConnectivityInsights#48](https://github.com/camaraproject/ConnectivityInsights/issues/48) which I have created there). One cause of this overlap is that neither DeviceStatus nor ConnectivityInsights has raised within APIBacklog their intent to define such API and that they want to include it into the scope of their Sub Project.
> 
> My proposal would be to create an issue within APIBacklog for the scope enhancement and use that as a trigger for the discussion in which Sub Project the API will be allocated.

As per agreed action API Backlog meeting 11th July, I have created. a [Scope Enhancement issue]( (https://github.com/camaraproject/APIBacklog/issues/66) . This is intended as input to the connected-network-type API discussion.

**Comment by Kevsy** [comment]
This appears to now fall under [PR 158 in Device Status](https://github.com/camaraproject/DeviceStatus/pull/158), so recommend to close this issue.

**Comment by gmuratk** [comment]
> @gmuratk now we should continue working on this. As discussed in our last community call, we are still not confident about the possible implementation on the 3GPP side. Could you please provide some information about it?

@akoshunyadi I think it's fair to expect network operators to determine the network their subscriber/device is connected to and there could be different implementations.  One option may use 3GPP Monitoring Event API, which offers connection information.
