### ISSUE TITLE
Simplification of Device object - short term solution

### ISSUE THREAD

**Issue by rartych** [camaraproject/DeviceStatus#157]
**Problem description**

Commonalities discussed the topic and proposed the short term solution (for the coming meta-release) summarized in  https://github.com/camaraproject/Commonalities/issues/171#issuecomment-2129218755 :

- Apply the mechanism to rely on the access_token (not providing the device object in the API request) for 3-legged access scenarios.
- Remove the networkAccessIdentifier from Device object

Reviewing and providing the feedback on the impact of the proposed solution on this subproject was suggested by the TSC.

**Possible evolution**
Review the proposed changes before Commonalities meeting on 10.06. https://github.com/camaraproject/Commonalities/issues/171

**Alternative solution**
Review the PR related to https://github.com/camaraproject/Commonalities/issues/171 (should be created soon)

**Additional context**
Initial proposal of text explaining using access token information to identify the target device of the API request: https://github.com/camaraproject/Commonalities/issues/171#issuecomment-2133228135
Dedicated meeting summary:
https://wiki.camaraproject.org/display/CAM/2024-05-23+-+Commonalities+Ad-Hoc+Meeting+-+Device+Object+review

**Comment by akoshunyadi** [comment]
Decision from community call, the issue can be closed, and a long term solution should be elaborated
