### ISSUE TITLE
Align subscription APIs with new template

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#162]
**Problem description**
The newly created subscription APIs (roaming and reachability) need to be updated to comply with the [subscription template](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml)

**Possible evolution**
Create a PR to adapt both APIs. No additional changes should be made.

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
@akoshunyadi This one could be closed
