### ISSUE TITLE
Change Subproject Scope

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/DeviceStatus#163]
I propose expanding the scope of this subproject to include all mobile connection standards. Right now the scope is limited to 4G and 5G. Ensuring that our APIs are standardized across different mobile network technologies will enhance their versatility and usability. 

I would suggest: 
1. Either to delete the "Note" Statement complete 
2. Or to expand the scope also to 2G, 3G in the Note.

**Comment by sachinvodafone** [comment]
good observation @NoelWirzius . My suggestion is to expand the scope of this subproject to include support for 2G and 3G alongside 4G and 5G.
