### ISSUE TITLE
Check the Overlap between DeviceStatus and ShutdownServiceStatus

### ISSUE THREAD

**Issue by chinaunicomyangfan** [camaraproject/DeviceStatus#167]
**Problem description**

Based on the decision of the APIBacklog meeting, we need to discuss whether there is any overlap between DeviceStatus and [ShutdownServiceStatus](https://github.com/camaraproject/APIBacklog/pull/32/files?short_path=33ea39f#diff-33ea39f607d82cb11a75668e0f7bfd1d14d90c98ddcc26c8763706201922e553).

**Introduction**
ShutdownServiceStatus API allows users to obtain the current shutdown status of a phone number, including voice/SMS incoming shutdown, voice/SMS outgoing shutdown, and data service shutdown.
This API queries the business shutdown status of the number, for example, due to overdue payments.

**Use Case**
Payment System and Risk Management: In scenarios where payment or identity verification relies on phone numbers, such as e-commerce platforms or financial service providers, this API can be used to verify whether user accounts are functioning properly. This helps to reduce fraud and payment risks, ensuring that only normal accounts can conduct transactions.

**Opinion**
I think the main difference between ShutdownServiceStatus and device status is that DeviceStatus obtains the device's connection status, while ShutdownServicestatus obtains the business status of the phone number. When a user turns off the phone, the connection status is closed, but the business status is open.

**Comment by akoshunyadi** [comment]
@chinaunicomyangfan 
DeviceStatus API currently offers the check of the connectivity status, which can be not-connected. 
If I understand it correctly, the new API should check whether the SIM card has an active subscription e.g. for data, right?

ShutdownServiceStatus sounds little confusing, something like SubscriptionStatus would be clearer.

**Comment by chinaunicomyangfan** [comment]
@akoshunyadi 
Yes,I think you are right.ShutdownServiceStatus is used to describe situations where phone numbers are overdue, unusable, or cancelled. Different countries have different descriptions as well.If SubscriptionStatus is more general and clear, we can consider modifying the API name

**Comment by chinaunicomyangfan** [comment]
@akoshunyadi 
Yes,I think you are right.ShutdownServiceStatus is used to describe situations where phone numbers are overdue, unusable, or cancelled. Different countries have different descriptions as well.If SubscriptionStatus is more general and clear, we can consider modifying the API name

**Comment by sachinvodafone** [comment]
"DeviceSubscriptionStatus" could be  another option in this case.

**Comment by chinaunicomyangfan** [comment]
> "DeviceSubscriptionStatus" could be another option in this case.

@sachinvodafone  Thank you for your suggestion.

**Comment by ShutingQing** [comment]
Subscription is accurate. Suggest to consider subscription as an option in naming. However, should this be the business status of phone number, instead of device? I think it's a good option to name it as SubscriptionStatus or ServiceSubscriptionStatus. @chinaunicomyangfan
