### ISSUE TITLE
Make Device attribute optional in device-roaming-status & device-reachability-status

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceStatus#173]
**Problem description**
As discussed in Commonalities issue#[171](https://github.com/camaraproject/Commonalities/issues/171) & [PR233 ](url)we need to shift the `device` object to optional. 

**Expected behavior**
Apply the mechanism to rely on the access_token (not providing the device object in the API request) for 3-legged access scenarios. This would fix interoperability in all these scenarios, which is a huge improvement. We can define the device identifier as optional in the API specification and, if not provided, simply refer to access_tokehttps://github.com/camaraproject/Commonalities/pull/233n. The developer would simply not provide any further device information, which is simpler. The operator does not need to check that the device identifier actually matches the access_token provided and could simply rely on the access_token itself.

**Alternative solution**

**Additional context**

**Comment by maxl2287** [comment]
Hi @bigludo7, 
is this also required for the subscription-APIs?

**Comment by bigludo7** [comment]
> Hi @bigludo7, is this also required for the subscription-APIs?

Fair question !
The subscription will be handled by 3-legs so I guess getting the phone number via the access token is perfectly valid... consequently the phone number could be optional.
So regarding your question for me Yes 

To simplify our work we can probably craft 2 PR: one under your name for the 2 subscriptions yaml and one for me for the 2 other APIs. Works for you?

**Comment by maxl2287** [comment]
@bigludo7, Sure :)
