### ISSUE TITLE
Proposed Sub-Project Scope Enhancement: Device Quality Indicator API

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/DeviceStatus#176]
**Problem description**
On behalf of the Open Gateway Product Workstream, Deutsche Telekom (via @NoelWirzius) have introduced a new [Device Quality Indicator](https://github.com/camaraproject/APIBacklog/issues/19) API proposal to the API Backlog WG, and Vodafone are amongst the supporters of this proposal. The API description can be found [here](https://github.com/camaraproject/WorkingGroups/blob/6c82697b2b87ba186955fd0c6e41ba478dd5a642/APIBacklog/documentation/SupportingDocuments/API%20proposals/APIProposal_Device_Connection_Quality_Indicator.md), and I also replicate the description below:

*The API enables App Developers to get insights about the network status of a defined mobile device. For this the API will return an indicator which is bundling information about the device network status such as availability, open data volume, congestion, historical congestion or the connectivity status (2G, 3G, 4G, 5G). The API service will also alert the consumers when an indicator changes. This API would be useful for applications that optimize user experience based on the connectivity status of a defined device.*

The "indicator" would probably follow the traffic light (RAG) standard, but still to be agreed.  "Open data volume" would be obtained from a new API - [Device Data Volume](https://github.com/camaraproject/APIBacklog/issues/28) - and the two APIs would be developed jointly.

The two APIs have been approved, but need a home

**Possible evolution**
During discussion in API Backlog, it was agreed that the existing Device Status Sub-Project would be the best fit for these two APIs. The proposal is to create a **separate repository or repositories** for these APIs, but discuss them within the existing Device Status meetings (as envisaged by the agreed proposal on "[API Families](https://github.com/camaraproject/Governance/issues/142)").

Although it is proposed that the new API will also make use of the Connectivity Insights API in addition to the existing Device Status API when constructing the bundled metric, the Device Status Sub-Project was identified as being a better fit as the home for these new APIs as the usage model (one off requests or status change alerts) is the same as that adopted by Device Status, rather than the "monitoring" approach adopted by Connectivity Insights.

I'm opening this issue to formally request that the Device Status Sub-Project adopt these APIs as part of the Device Status family.

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
This is fine for Orange to welcome Device Quality Indicator API in our sub-project :)

**Comment by hdamker** [comment]
Deutsche Telekom supports the adoption of the two APIs within the "family" of DeviceStatus. Obviously :)

**Comment by eric-murray** [comment]
@camaraproject/device-status_maintainers
I wasn't able to join the meeting today. Is it now approved that these two APIs can be part of the Device Status sub-project? Thanks.

**Comment by NoelWirzius** [comment]
@eric-murray yes it is approved, but will not be in scope for the 0.6.0 (Fall release) of Device Status.

**Comment by eric-murray** [comment]
Closing as completed
