### ISSUE TITLE
Create release candidate #1 for Fall24 CAMARA release

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#177]
**Problem description**
The release candidates for Fall24 release should be created.

**Expected action**
- create PR to prepare the release
  - change API version in all 4 OASs to 0.6.0-rc.1
  - change URL in all 4 OASs (server object) to v0.6rc1
  - update changelog.md
  - update readme.md
  - add readiness checklist for all 4 APIs
-  create subproject release r1.1

**Additional context**
Scope of the release: #172

**Comment by hdamker** [comment]
@akoshunyadi 

> * create subproject release r0.7

As mentioned also with the draft PR: the release number should be r1.1, as the first release within the Fall24 release cycle (cf. https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API_Release_Guidelines.md)

API Version 0.6.0-rc.1 looks correct to me.

**Comment by akoshunyadi** [comment]
Description updated to release 1.1
