### ISSUE TITLE
More Details for Roaming Status 

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/DeviceStatus#18]
**Summary**
===========
Expanding the roaming status with additional informations, which can help the developer to improve application. Example to set the right profiles for them.  

**Changes** 
==========
*Adding new return parameters 
  * Country Code 
    * Is the Code of the country where the device is 
  * Country Name  
    * Is the Name of the country where the device is

**Comment by sachinvodafone** [comment]
I would recommend to have following in response apart from roaming status:

- "Home_PLMNid"
- "Visited_MNC"
- "Visited_MCC"

**Comment by yoonsun3** [comment]
I think we can also offer roaming operator information from PLMN. But, it seems to be difficult to match and manage the Operator Code and Operator Name.

- Operator Code (MNC)
    - Is the Code of the operator where the device is
- Operator Name
    - Is the Name of the operator where the device is

**Comment by eric-murray** [comment]
I would avoid returning home PLMN Id as part of the roaming report as that is really a different use case unrelated to roaming. There may be reasons why an API caller wants to know with which mobile operator a given subscriber (MSISDN) has a contract, but that is a different type of status, so should at least be a different path, if not a different API, as they should not have to call a "roaming status" path to get this information. It would also require separate user consent.

I would also avoid returning Operator Name. Knowing the visited PLMN Id would allow the API caller to determine this for themselves if they really wanted to know, but it would be difficult for the API provider to do this reliably and I think this would be an unnecessary  overhead.

**Comment by yoonsun3** [comment]
I also agree that there will be no case to use the operator information. I just suggested that because it would be like to create a standard with optional parameters so that information can be returned, if possible.

**Comment by akoshunyadi** [comment]
Do we have a common understanding, whether these 2 new fields (country name and code) should be included in the response also for the home network?

**Comment by eric-murray** [comment]
@akoshunyadi 

Do you mean when a mobile is not roaming? For a German mobile subscription, for example:
```
{
    roaming: false
    countryCode: 262
    countryName: ["DE"]
}
```

I'd say that was up to the implementation but, knowing the identity of the UE, it is not hard to work out what country is the home country. But `countryCode` and `countryName` are both optional, so it is valid not to include them.

**Comment by sachinvodafone** [comment]
I agreed with @eric-murray for not including countrycode and countryName if person is not in roaming. It is not relevant.

**Comment by NoelWirzius** [comment]
Closing this issue
