### ISSUE TITLE
Align subscription-APIs with guidelines for error scenarios

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#184]
**Problem description**
Current version still does not follow the recent guidelines.

**Possible evolution**
Align codes and examples as indicated in:

https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml

**Comment by akoshunyadi** [comment]
We've aligned with the event-subscription-template.yaml, shouldn't that be first aligned with the guideline? @bigludo7

**Comment by bigludo7** [comment]
> We've aligned with the event-subscription-template.yaml, shouldn't that be first aligned with the guideline? @bigludo7

Yes! we need to align our template yaml with the commonalities. 
@maxl2287 have you already done the gap list?
