### ISSUE TITLE
Adding "unkown" 

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/DeviceStatus#19]
**Summary**
===========
It can happen that the network can't locate the device, because it is offline and the location is also not cached. In this there should be coming the right response from the API. 

**Changes** 
==========
Adding to `true` or `false` the return value `unkown`, when it is not possible to get the location

**Comment by jlurien** [comment]
@NoelWirzius Write issue, wrong API :) please move this to DeviceLocation
