### ISSUE TITLE
Tag version 0.2.0

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/DeviceStatus#24]
Could the project kindly create a tag for 0.2.0?

**Comment by hdamker** [comment]
@eric-murray as this has to be done by one of the codeowners - would you be so kind to take it?

**Comment by eric-murray** [comment]
@hdamker Yes, I can do this.

**Comment by hdamker** [comment]
@eric-murray the release looks good for me!

Regarding protecting the release-* branches you are right - they should be protected. I suppose it would make sense to create a rule for that in all sub projects  @shilpa-padgaonkar what do you think? Could that be an issue for commonalities (small addition to release guidelines) and then we can implement it across the project?

**Comment by shilpa-padgaonkar** [comment]
Release LGTM as well.
Yes, makes sense to add it as a rule in the release guidelines. @hdamker : Would you like to open a PR? :)

**Comment by hdamker** [comment]
All branches with `*release* are now protect with same settings than `main`. 
Issue to update release guidelines created in Commonalities: https://github.com/camaraproject/WorkingGroups/issues/186
