### ISSUE TITLE
API Base Path

### ISSUE THREAD

**Issue by sachinvodafone** [camaraproject/DeviceStatus#26]
Hi All, 

Currently we have defined following base path for device status:

basePath:
        default: connectivity/v0
        description: Base path for Device Connectivity API

If we will go with this approach then we will have to create a new proxy if version change from V0 to V1. Please correct me if my understanding is wrong.

**Comment by eric-murray** [comment]
What's the difference in implementation between:

```
servers:
  ...
      basePath:
        default: qod/v0
paths:
  /sessions:
```
and
```
servers:
  ...
      basePath:
        default: qod
paths:
  /v0/sessions:
```
That's a rhetorical question, by the way - there is no difference (or, at least, no need for any difference).

I don't think having `/v0` defined in `basePath` forces implementors to adopt one approach or another when it comes to proxy implementation in the unlikely event that it is desired to maintain multiple versions. CAMARA is about defining APIs that are easy for clients to use, and not necessarily ones that are easy for automatic code generators to implement. The YAMLs themselves will only be for a single version, so `v0` and `v1` will not have to co-exist within the same YAML.

If you still have doubts, move this issue to Commonalities.

**Comment by sachinvodafone** [comment]
Thanks @eric-murray for your valuable inputs.  Interestingly, I found the response in google community with recommendation to include version information in basepath and  create different proxy for the same. 

https://www.googlecloudcommunity.com/gc/Apigee/Maintaining-multiple-versions-of-a-proxy/m-p/38703


However, In [OpenAPI3.0](https://swagger.io/docs/specification/api-host-and-base-path/), basePath is no longer a top-level property. Instead, API Gateway uses a [server variable](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverVariableObject) as a convention.

We can close this issue.
