### ISSUE TITLE
Typo in response parameter countryName description

### ISSUE THREAD

**Issue by monamok** [camaraproject/DeviceStatus#27]
In this [PR](https://github.com/camaraproject/DeviceStatus/pull/21#discussion_r1106682523) we decided to go with empty array for  "No associated country" case but the description still says ["xx"].

<html><body>

countryName | Array of strings (CountryName)  The  ISO 3166 ALPHA-2 country-codes of mapped to mobile country code(MCC).  If there is mapping of one MCC to multiple countries, then we have list  of countries. If there is no mapping of MCC to any country, then ["xx"]  will be used.
-- | --

</body>
</html>

@ravindrapalaskar17 could you fix it please?

**Comment by monamok** [comment]
@NoelWirzius @eric-murray @bigludo7 @sachinvodafone 
Due to the last changes applied, I also would like to propose to rename the YAML file from "check-device-connectivity" to "check-device-status" or "device-status" or the name you find more suitable.

I can open a PR and include both fixes depending on your preferences.

**Comment by eric-murray** [comment]
Why not call the file "CAMARA Device Status API.yaml"? The inability of many developers to properly write or test their scripts should not prevent us from having spaces in filenames. They have, after all, been properly supported by all file systems for a very long time now.

**Comment by ravindrapalaskar17** [comment]
> In this [PR](https://github.com/camaraproject/DeviceStatus/pull/21#discussion_r1106682523) we decided to go with empty array for "No associated country" case but the description still says ["xx"].
> 
> countryName	Array of strings (CountryName) The ISO 3166 ALPHA-2 country-codes of mapped to mobile country code(MCC). If there is mapping of one MCC to multiple countries, then we have list of countries. If there is no mapping of MCC to any country, then ["xx"] will be used.
> @ravindrapalaskar17 could you fix it please?

Yes.. I will fix the same Should We reopen the Existing PR ..?

**Comment by eric-murray** [comment]
@ravindrapalaskar17
New PR. Version 0.4.1

Do we want to continue the discussion on the filename here? It is not really relevant to this specific issue. If not, we can close this issue, and create a new issue if someone wants to further discuss the yaml filename.

**Comment by eric-murray** [comment]
PR merged. Issue can be closed.
