### ISSUE TITLE
Get status for multiple devices

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#29]
In this issue we would like to enable to retrieve the device status (currently only roaming) for multiple devices in one call.

## Change:
Request: instead of 1 device a list of devices should be used
Response: instead of 1 response object a list of responses should be used, one for each device

**Comment by eric-murray** [comment]
Additional questions - what is the maximum proposed list size, and what happens if the list is anyway so large that the response cannot be  provided synchronously due to the time required to get the information and construct response json?

**Comment by akoshunyadi** [comment]
After the discussion in the bi-weekly call the issue will be closed. Multiple devices shall be better introduced in the subscription/event based queries.
