### ISSUE TITLE
New Endtype Connectivity 

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/DeviceStatus#34]
**Summary**
===========
In this issue will add a new **Endpoint** which helps to get the current connectivity status. 

**Changes** 
==========
* Adding new Endpoint
    * /connectivity
      * This will give back if the device is currently connected to a network or not (DATA)

**Comment by bigludo7** [comment]
About adding resource we should follow the issue https://github.com/camaraproject/WorkingGroups/issues/178

**Comment by akoshunyadi** [comment]
I guess the idea is to have a new endpoint like /connectivity
it means eventType is wrong here

**Comment by NoelWirzius** [comment]
@Working Group take a look at these topic and make suggestions until next meeting.

**Comment by eric-murray** [comment]
I discussed this internally within Vodafone, and there was a clear preference to implement additional statuses as separate APIs, with a single endpoint per API. The primary reason for this was flexibility in implementation and API management, which was also mentioned by @bigludo7 as a benefit of this approach. However, it was accepted that both approaches could be made to work.

So Vodafone's preference is for a second API to be defined for the connectivity status.

**Comment by monamok** [comment]
As it was already mentioned in commonalities issue, TEF's preference is having separated APIs for different functionalities.
Another PRO for it is that we avoid partial implementations in case someone is interested in one of the endpoints/functionalities and not the others.

**Comment by akoshunyadi** [comment]
[Decision supporting document 1 or 2 APIs](https://github.com/camaraproject/DeviceStatus/blob/main/documentation/SupportingDocuments/decision-support-1-or-2-apis.md)

**Comment by eric-murray** [comment]
Poll result was to add an additional endpoint to existing basepath. See https://github.com/camaraproject/DeviceStatus/discussions/55.

**Comment by bigludo7** [comment]
Thanks @eric-murray 
I propose to rework https://github.com/camaraproject/DeviceStatus/pull/31 to integrate this decision (2 endpoints + subscriptions)- is it ok?

**Comment by eric-murray** [comment]
@bigludo7
Yes, for adding subscriptions, I'm happy to have a common endpoint here.

For connectivity status itself, mobile networks have a number of different states that could be considered "connectivity status", so I consider that the definition(s) that we will adopt for this API is/are still open. So we should keep this issue open to discuss that.

@monamok
Yes, that is a weakness of github polls. In fact, it could have been any github member who cast the additional vote, and not necessarily a participant of this sub-project. However, the declared votes still have a majority for Option 1, so I don't think this invalidates the result. I'm hoping the new governance process and Technical Steering Committee will remove the need to use such polls for major design decisions.

**Comment by monamok** [comment]
@eric-murray thank you. Yes, the result will be still the same so in case it's not relevant.


Now that it was decided to add new endpoints to the same API I have another question.
There are still some details to adjust but we're almost done with the roaming status endpoint and as soon as the subscriptions endpoint is added, it can lead to have a release (potentially v1.0). 
If we start with new functionalities such as connectivity, as we haven't started to yet discuss them, the timelines can totally change. I think it would be interesting if we could talk about the v1.0 scope and see what to include or not. Otherwise there's no way to have a release as it can always expand with new types of device statuses related functionalities. What do you think about this?

**Comment by eric-murray** [comment]
@monamok
Yes, I think a release with roaming status + subscriptions before adding connectivity is a good idea. We can discuss what version number to give this in the next meeting.

Note that roaming subscriptions may require some further discussion. Does the API consumer get a notification when the roaming status itself changes (i.e. only when they leave or return to their home network), or when the visited country changes (so roaming status itself does not change), or even when the visited network changes? Can they choose between these options?

**Comment by bigludo7** [comment]
@eric-murray @monamok  @akoshunyadi @JoachimDahlgren 

 Please consider https://github.com/camaraproject/DeviceStatus/pull/31
I've aligned with guideline + provided several envent type in order to be precise + solved issue for https://github.com/camaraproject/DeviceStatus/issues/52

**Comment by monamok** [comment]
Thank you @bigludo7. I added some comments, suggestions and points to discuss about in the PR. 

P.D. Tomorrow I'm not gonna be able to connect to the meeting. I'll be folowing up on the comments and the MoM once they're published.

**Comment by eric-murray** [comment]
I'd like to move this discussion on to defining what we mean by "connectivity status".

Considering the connectivity status of mobile devices, and assuming that the network element providing this status is the NEF, is it proposed that the monitoring event that will give this status is `UE_REACHABILITY` and, given that we are interested in data connectivity, the `reachabilityType` should be `DATA`?

There are other NEF monitoring types associated with data connectivity, particularly `PDN_CONNECTIVITY_STATUS`. However, I assume that if  `PDN_CONNECTIVITY_STATUS` information is returned, then  `UE_REACHABILITY` would also return a  `reachabilityType` value of `DATA`, and hence the additional information returned by that monitoring type (such as IP addresses or APN used) would only become application if we wanted to return that data as well.

Let me know if you have a different view.
