### ISSUE TITLE
Create release 0.4.0

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#37]
As decided in our regular call we'd like to create a new release 0.4.0. This should be done by one of the code owners.
However maybe we should discuss again, if it's necessary, or we're targeting only the 0.5.0.

**Comment by eric-murray** [comment]
I created release v0.4.1 (it was easier than looking back for v0.4.0). I note that the documentation has not been updated for this release - any volunteers? If someone does update it, can you merge to the release-0.4.1 branch first, so the documentation is correct for the release. Thanks.

**Comment by NoelWirzius** [comment]
@akoshunyadi  will take over the documentation
