### ISSUE TITLE
Link to wrong discussions in config of issue templates

### ISSUE THREAD

**Issue by hdamker** [camaraproject/DeviceStatus#42]
**Problem description**

Link in https://github.com/camaraproject/DeviceStatus/blob/main/.github/ISSUE_TEMPLATE/config.yml is pointing to discussions in repo WorkingGroups instead to the ones in the sub project itself (where questions about the DeviceStatus API should go).

**Expected action**

a) Enable discussions in the sub project (I can do that, just let me know if you want to have them in the sub project)
b) Change the URL in https://github.com/camaraproject/DeviceStatus/blob/main/.github/ISSUE_TEMPLATE/config.yml

Alternative would be to delete the section about discussions from the config.yml

**Additional context**

**Comment by hdamker** [comment]
Just recognized that the use of the template haven't created the respective label ("subproject management"). I'm checking with the template author if this should happen automatically.

**Comment by eric-murray** [comment]
@hdamker 
I'm happy to change the link if you enable Discussions, which I was not able to do.

This comment also applies to the Anonymised Subscriber Identifier and Device Identifier sub-projects.

**Comment by hdamker** [comment]
@eric-murray done here. will do for the other projects as well
