### ISSUE TITLE
Harmonize device object with QoD API

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#52]
**Problem description**
After the consensus on the definition of the device object in the QoD API, other API specs should be harmonized.

[Glossary](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md)
[QoD API](https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qod-api.yaml)

**Expected behavior**
The property ueId and the subelements should be renamed and harmonized.

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
@akoshunyadi  - to be sure to be on same page - this issue is to align device definition as in QoD API -  correct ?

```json
"device": {
    "phoneNumber": "123456789",
    "networkAccessIdentifier": "123456789@domain.com",
    "ipv4Address": {
      "publicAddress": "84.125.93.10",
      "publicPort": 59765
    },
    "ipv6Address": "2001:db8:85a3:8d3:1319:8a2e:370:7344"
```

**Comment by akoshunyadi** [comment]
@bigludo7  yes, exactly

**Comment by akoshunyadi** [comment]
Fixed by [ Adding notification/subscription for Device Status #31](https://github.com/camaraproject/DeviceStatus/pull/31)
