### ISSUE TITLE
Meetings ?

### ISSUE THREAD

**Issue by GarethWGSMA** [camaraproject/DeviceStatus#7]
Hi,

Gareth here from GSMA - have got a time arranged for meetings ? I can't find it anywhere.

Thanks

**Comment by eric-murray** [comment]
I have organised a one-off meeting for Monday 12th December @ 15:00 GMT / UTC. You'll find the meeting link and a handy calendar file [here](https://lists.camaraproject.org/g/sp-dst/topic/camara_device_status_wg/95562791?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,95562791,previd%3D1670601033197497782,nextid%3D1666709801536698064&previd=1670601033197497782&nextid=1666709801536698064).

**Comment by eric-murray** [comment]
Keep open until bi-weekly meetings scheduled

**Comment by MarkusKuemmerle** [comment]
@bigludo7 @jlurien : Would you please insert the meeting data in the Readme.md of the Sub Project?

**Comment by eric-murray** [comment]
Hi @MarkusKuemmerle

I had understood that @NoelWirzius would be chairing this WG on an ongoing basis? Is that not the case? If it will not be chaired by Deutsche Telekom, then I am quite happy for Orange to chair it :-)

**Comment by NoelWirzius** [comment]
@eric-murray  i will take over and will set up a call end of this month

**Comment by NoelWirzius** [comment]
Bi weekly meeting 11 Cet starting from 1 feb

**Comment by eric-murray** [comment]
Meeting series now created
