### ISSUE TITLE
Info required : API understanding 

### ISSUE THREAD

**Issue by psidana1983** [camaraproject/DeviceStatus#70]
Hi team, 

Can you please help me to understand the use case for endpoint "/roaming"  where i shall expect the response to have 
a valid country code but no country name 
a valid country code with multiple country names

Regards
Prashant Sidana

**Comment by bigludo7** [comment]
@psidana1983 
From my perspective we can have country code linked to several countries or at least to several territories (340 for example covers distinct French territories with distinct country code iso).
I'm not sure about valid country code with no country name - perhaps for international operators on maritime or space scope (see code 901).

**Comment by akoshunyadi** [comment]
@psidana1983 can you please close the issue, if already solved?
