### ISSUE TITLE
Release plan&content

### ISSUE THREAD

**Issue by rartych** [camaraproject/DeviceStatus#71]
**Problem description**
As discussed in the last meeting we should decide about content of the next pre-release (v.0.5.0).

**Expected action**
Currently we have 2 PRs open:

- one deals with documentation and discussion covers also notifications to be aligned with new guidelines
- the other proposes /connectivity endpoint

Please provide your views on content and possible timeline for the next API release.

**Additional context**
In  this [comment](https://github.com/camaraproject/DeviceStatus/pull/69#issuecomment-1680557106) Eric proposed to wait with /connectivity endpoint to v.0.6.0

**Comment by akoshunyadi** [comment]
@rartych I think this issue can be closed, since we're tracking the release planning in the MoMs

**Comment by rartych** [comment]
@akoshunyadi Yes!

**Comment by rartych** [comment]
Closing as agreed above.
