### ISSUE TITLE
Align event-subscriptions with updated design guidelines based on CloudEvents

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#74]
**Problem description**
After approving [PR56 Update DG with use of callbacks & cloudEvents](https://github.com/camaraproject/Commonalities/pull/56) the DeviceStatus API definition needs to be updated too.

**Expected behavior**
Update the event-subscription related parts in the API spec based on the updated DG

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
Agreed.
Probably we should close https://github.com/camaraproject/DeviceStatus/pull/65 and crreate a new PR for that ?

**Comment by akoshunyadi** [comment]
Updated the original issue, by removing point #2.
