### ISSUE TITLE
Path update per Design Guideline

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/DeviceStatus#96]
**Problem description**
Following paths must be verbs per design guideline:
/connectivity
/roaming

From Design Guideline:
> When the POST method is used, the resource in the path must be a verb (e.g. retrieve-location and not location) to differentiate from an actual resource creation.

**Expected behavior**
"/connectivity" may be changed to "/retrieve-connectivity-status"
and
"/roaming" may be changed to "/retrieve-roaming-status"

**Alternative solution**

**Additional context**

**Comment by sachinvodafone** [comment]
I've observed that some APIs within Camara incorporate the term "get" as a verb in their endpoints. Therefore, it is essential to ensure consistency in the naming conventions for actions associated with all APIs whether to use "get" or "retrieve"

**Comment by bigludo7** [comment]
Agreed with this request and that we should change our path as `POST /roaming` or `POST /connectivity` are confusing.

We can follow guideline (probably we're supposed to do this way) but looking to device-locatin API family I saw following path: `location-retrieval` and `location-verification`....

So not sure if we move to alignement with the rule (`retrieve-roaming-status` and `retrieve-connectivity-status`) or to be consistent (`connectivity-status-retrieval` and `roaming-status-retrieval`).

**Comment by gmuratk** [comment]
@akoshunyadi: I tried to resubmit (twice) but it doesn't appear in the list of PRs.  Let me know please if you don't see the PRs.

**Comment by akoshunyadi** [comment]
@gmuratk I can see the PR, but it is a PR against your forked main and not the official main, that's why it doesn't appear at the PRs above

**Comment by gmuratk** [comment]
Thanks @akoshunyadi !  I think this time I reopened it in the right place successfully.
see PR #131
