### ISSUE TITLE
Update response codes to string, following other CAMARA APIs

### ISSUE THREAD

**Issue by mhfoo** [camaraproject/DeviceStatus#97]
**Problem description**
The response codes are currently in integer format. Propose to update to string.

**Expected behavior**
Update the YAML file use string for the response code

**Alternative solution**
N.A

**Additional context**
This was flagged out in other sub-projects.
[Telco Finder](https://github.com/GSMA-Open-Gateway/Open-Gateway-Documents/pull/95)

**Comment by mhfoo** [comment]
8< -----------------------------
There is no commonalities guideline, I'd say it's not needed as are keys of a dictionary and OAS spec says: Any [HTTP status code](https://swagger.io/specification/#http-codes) can be used as the property name, but only one property per code, to describe the expected response for that HTTP status code. This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.

**Comment by mhfoo** [comment]
8< -----------------------------
There is no commonalities guideline, I'd say it's not needed as are keys of a dictionary and OAS spec says: Any [HTTP status code](https://swagger.io/specification/#http-codes) can be used as the property name, but only one property per code, to describe the expected response for that HTTP status code. This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.

**Comment by hdamker** [comment]
@mhfoo As far as I can see this correction is already part of #95. Can you check and confirm?

**Comment by mhfoo** [comment]
> @mhfoo As far as I can see this correction is already part of #95. Can you check and confirm?

@hdamker 
Yes, it is included. Thanks.

**Comment by akoshunyadi** [comment]
#95 has been merged, so the issue can be closed.
